### ISSUE TITLE
Issue when trying to copy types

### ISSUE THREAD

**Issue by xtrinch** [cloudbeds/webpack-module-federation-types-plugin#23]
The app own types are generated correctly inside the `build/@types` folder:

```
/// <reference types="react" />
declare module "app2/Button" {
    import { FC } from "react";
    const Button: FC<{
        className?: string;
    }>;
    export default Button;
}
```

But there is an error when the plugin tries to get the remote's typings:

```
app2: <w> [ModuleFederationTypesPlugin] Failed to load remote types from: http://localhost:3002/@types/index.d.ts
app2:     [ModuleFederationTypesPlugin] GotError [HTTPError]: Response code 404 (Not Found)
```

So my `src/@types/remotes/app2` folder is created but there's nothing in there.

My federation configs:

app1 (PORT=3000):
```
 const deps = require("./package.json").dependencies;

module.exports = {
  name: "app1",
  exposes: {
  },
  remotes: {
    app2: "app2@http://localhost:3002/remoteEntry.js",
  },
  filename: "remoteEntry.js",
  shared: {
    ...deps,
    react: {
      singleton: true,
      requiredVersion: deps["react"],
    },
    "react-dom": {
      singleton: true,
      requiredVersion: deps["react-dom"],
    }
  },
};

```

app1 (PORT=3002):
```
const deps = require("./package.json").dependencies;

module.exports = {
  name: "app2",
  exposes: {
    "./Button": "./src/Button/index",
  },
  filename: "remoteEntry.js",
  remotes: {
  },
  shared: {
    ...deps,
    react: {
      singleton: true,
      requiredVersion: deps["react"],
    },
    "react-dom": {
      singleton: true,
      requiredVersion: deps["react-dom"],
    },
  },
};
```

I really don't see what it is I'm doing wrong. Any ideas?

EDIT: My app is actually served from /public, but I don't seem to be able to modify the destination directory, because it defaults to `dist/${dirEmittedTypes}`
What I would essentially need, is to configure it like this:
```
        new ModuleFederationTypesPlugin({
          downloadTypesWhenIdleIntervalInSeconds: 0,
          dirEmittedTypes: "public/@types" <----- currently the files will be written into `build/public/@types` instead of `public/@types`
        }),
```

EDIT2: I'm guessing my problem is the way the directory to save files in is determined:
https://github.com/cloudbeds/webpack-module-federation-types-plugin/blob/645f64389a0847c76498c9055c04903114269e14/src/plugin.ts#L70
But I'm using CRA so maybe they don't set these variables as this plugin presumes they do?

EDIT3:
setting `webpackConfig.output.path = join(process.cwd(), "public")`
does fix the problem for me, but it seems very very hackish

**Comment by steven-prybylynskyi** [comment]
Hey @xtrinch, sorry for the late response, somehow this issue was missed.

Are you referring to https://github.com/cloudbeds/webpack-module-federation-types-plugin/blob/645f64389a0847c76498c9055c04903114269e14/src/helpers/downloadTypes.ts#L119? Is it still relevant?

**Comment by xtrinch** [comment]
Yep still relevant, it's about the line in the original issue

**Comment by steven-prybylynskyi** [comment]
I see, its in EDIT2, will work on it on the weekend
