### ISSUE TITLE
GET request rejected due to not having an accept header

### ISSUE THREAD

**Issue by amoestreich** [cloudbeds/webpack-module-federation-types-plugin#24]
I'm able to generate types fine but when I go to fetch them my host (using webpack-dev-server) rejects it with `[webpack-dev-server] [connect-history-api-fallback] Not rewriting GET /@types/index.d.ts because the client did not send an HTTP accept header.`
Is there somewhere I can insert this header? Or does anyone know of a webpack config that will allow this through without modification? 

Thanks in advance

**Comment by steven-prybylynskyi** [comment]
Not sure what the problem is, perhaps adding `historyApiFallback: true` to `devServer` config helps
