### ISSUE TITLE
Using the CLI tool inside a monorepo can break because separate node_modules location

### ISSUE THREAD

**Issue by vjustov** [cloudbeds/webpack-module-federation-types-plugin#31]
We have an nx monorepo that looks like the example below. currently running `npx make-federated-types -c apps/app1/federation.config.js` from the root of the project causes the command to fail with `Error: Cannot find module '/Users/vjustov/tw/rb/experience-marketplace-mfpoc/tsconfig.json'`

```
- node_modules
- apps
- - app1
- - - federation.config.js (i'm using the -c param which btw is not yet in the readme.)
- - - tsconfig.json
- tsconfig.base.json
```

I've managed to monkeypatch the code on [this line](https://github.com/cloudbeds/webpack-module-federation-types-plugin/blob/main/src/helpers/compileTypes.ts#L13) to make it work for my case, but maybe it makes sense to be able to pass a tsconfig path as another cli option?

What do you think?

**Comment by steven-prybylynskyi** [comment]
Thx, added --tsconfig flag from https://github.com/cloudbeds/webpack-module-federation-types-plugin/pull/32
