### ISSUE TITLE
Compatibility with @module-federation/nextjs-mf

### ISSUE THREAD

**Issue by justLuiz** [cloudbeds/webpack-module-federation-types-plugin#34]
Hey, 
How can i use with `@module-federation/nextjs-mf`

i m trying download types from remote on next build, but nothing happens

**Comment by steven-prybylynskyi** [comment]
Sorry, I have no experience with `@module-federation/nextjs-mf`

I'll keep this thread open in case someone can help

If you find a solution, please share it in this thread

PRs are also anticipated

**Comment by justLuiz** [comment]
this occurs because on validation of the existence of the ModuleFederation plugin, in the case of `@module-federation/nextjs-mf`, the plugin has another name: `NextFederationPlugin` 

https://github.com/cloudbeds/webpack-module-federation-types-plugin/blob/3695665b03d9eeb98032f5a69d606a601a160941/src/plugin.ts#L60

I think that a possible solution would be to allow the name of the plugin to be configurable, via options.

if you agree with this approach i can open a PR

**Comment by steven-prybylynskyi** [comment]
Sorry for late reply, doesn't look clean, but if there's the only workaround then go ahead

**Comment by dhalbrook** [comment]
I'm running into this as well. Could we provide an option to pass the name of the MF plugin in the constructor, and a reference to an instance of it?

**Comment by steven-prybylynskyi** [comment]
Released with v1.14.0
