### ISSUE TITLE
Upgrade to version decompress - 4.2.1, decompress-tar

### ISSUE THREAD

**Issue by guywardrop** [cloudbeds/webpack-module-federation-types-plugin#43]
Hi, 

Security scan on the @cloudbeds/webpack-module-federation-types-plugin identified vulnerability in a dependent package: decompress-tar 4.1.1. The vulnerability is regarding Path Traversal via Network attack vector, as documented in https://cwe.mitre.org/data/definitions/22.html. 

Hoping it is possible for the team to upgrade to decompress-tar 4.2.1 as this package is highly useful but currently flagging too many critical vulnerabilities. 

Cheers

**Comment by steven-pribilinskiy** [comment]
Hey @guywardrop, I've bumped dependencies to latest versions

**Comment by guywardrop** [comment]
Hi Steven,

Much appreciated!

Cheers,

Guy
